// Owner spec: 001-verified-legal-engagement.
// Hand-trimmed ABI fragments — only the fns + events used by the platform.

export const attestationManagerAbi = [
  { type: 'error', name: 'NotOperator', inputs: [] },
  { type: 'error', name: 'NoSuchAttestation', inputs: [] },
  {
    type: 'function',
    name: 'SCHEMA_LAWYER',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'SCHEMA_CLIENT',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasCapability',
    inputs: [{ type: 'address' }, { type: 'bytes32' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLatestAttestationUid',
    inputs: [{ type: 'address' }, { type: 'bytes32' }],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'attestVerifiedLawyer',
    inputs: [
      { type: 'address', name: 'subject' },
      { type: 'string', name: 'jurisdiction' },
      { type: 'string', name: 'barAdmissionNumber' },
      { type: 'uint64', name: 'admittedAt' },
      { type: 'uint64', name: 'validUntil' },
    ],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'attestVerifiedClient',
    inputs: [
      { type: 'address', name: 'subject' },
      { type: 'string', name: 'countryOfResidence' },
      { type: 'bool', name: 'ageOver18' },
    ],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revokeCapability',
    inputs: [
      { type: 'address', name: 'subject' },
      { type: 'bytes32', name: 'schemaId' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Attested',
    inputs: [
      { type: 'address', indexed: true, name: 'subject' },
      { type: 'bytes32', indexed: true, name: 'schemaId' },
      { type: 'bytes32', indexed: false, name: 'attestationUid' },
    ],
  },
  {
    type: 'event',
    name: 'Revoked',
    inputs: [
      { type: 'address', indexed: true, name: 'subject' },
      { type: 'bytes32', indexed: true, name: 'schemaId' },
    ],
  },
] as const;

export const escrowAbi = [
  // Custom errors — viem decodes reverts via these.
  { type: 'error', name: 'NotEngagementClient', inputs: [] },
  { type: 'error', name: 'NotEngagementLawyer', inputs: [] },
  { type: 'error', name: 'NotEngagementParty', inputs: [] },
  { type: 'error', name: 'NotVerifiedClient', inputs: [] },
  { type: 'error', name: 'NotVerifiedLawyer', inputs: [] },
  { type: 'error', name: 'CooldownNotElapsed', inputs: [{ type: 'uint64', name: 'unlockAt' }] },
  { type: 'error', name: 'InvalidProposalState', inputs: [] },
  { type: 'error', name: 'InvalidEngagementState', inputs: [] },
  { type: 'error', name: 'ConflictProofFailed', inputs: [] },
  { type: 'error', name: 'NullifierAlreadyUsed', inputs: [] },
  { type: 'error', name: 'InvalidSplit', inputs: [] },
  { type: 'error', name: 'EthAmountMismatch', inputs: [] },
  { type: 'error', name: 'EngagementNotClean', inputs: [] },
  { type: 'error', name: 'TransferFailed', inputs: [] },
  { type: 'error', name: 'OnlyOperator', inputs: [] },
  { type: 'error', name: 'InvalidRefundSignature', inputs: [] },
  { type: 'error', name: 'InvalidOfferSignature', inputs: [] },
  { type: 'error', name: 'NonceAlreadyUsed', inputs: [] },
  {
    type: 'function',
    name: 'openFreeEngagement',
    inputs: [
      { type: 'address' },
      { type: 'bytes32' },
      { type: 'bytes' },
      { type: 'bytes32' },
      { type: 'bytes32' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'openPaidEngagementAndFundConsultation',
    inputs: [
      { type: 'address' },
      { type: 'bytes32' },
      { type: 'uint256' },
      { type: 'bytes' },
      { type: 'bytes32' },
      { type: 'bytes32' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'fundProposal',
    inputs: [
      { type: 'uint256' },
      { type: 'uint256' },
      { type: 'bytes32' },
      { type: 'bytes32' },
      { type: 'bytes' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'markDelivered',
    inputs: [{ type: 'uint256' }, { type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'releaseProposal',
    inputs: [{ type: 'uint256' }, { type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'mutualRefundProposal',
    inputs: [
      { type: 'uint256' },
      { type: 'uint256' },
      { type: 'bytes32' },
      { type: 'bytes' },
      { type: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'disputeProposal',
    inputs: [{ type: 'uint256' }, { type: 'uint256' }, { type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'escalateProposal',
    inputs: [{ type: 'uint256' }, { type: 'uint256' }, { type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resolveDispute',
    inputs: [
      { type: 'uint256' },
      { type: 'uint256' },
      { type: 'uint256' },
      { type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'closeEngagement',
    inputs: [{ type: 'uint256' }, { type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'anchorTranscript',
    inputs: [{ type: 'uint256' }, { type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getEngagement',
    inputs: [{ type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { type: 'address', name: 'client' },
          { type: 'address', name: 'lawyer' },
          { type: 'bytes32', name: 'matterRef' },
          { type: 'uint8', name: 'state' },
          { type: 'bytes32', name: 'transcriptRoot' },
          { type: 'uint256', name: 'proposalCount' },
          { type: 'bool', name: 'consultationPaid' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getProposal',
    inputs: [{ type: 'uint256' }, { type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { type: 'uint256', name: 'amount' },
          { type: 'uint8', name: 'state' },
          { type: 'uint64', name: 'deliveredAt' },
          { type: 'uint256', name: 'amountToLawyer' },
          { type: 'uint256', name: 'amountToClient' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'operator',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'EngagementOpened',
    inputs: [
      { type: 'uint256', indexed: true, name: 'engagementId' },
      { type: 'address', indexed: true, name: 'client' },
      { type: 'address', indexed: true, name: 'lawyer' },
      { type: 'bytes32', indexed: false, name: 'matterRef' },
      { type: 'bool', indexed: false, name: 'consultationPaid' },
    ],
  },
  {
    type: 'event',
    name: 'ProposalFunded',
    inputs: [
      { type: 'uint256', indexed: true, name: 'engagementId' },
      { type: 'uint256', indexed: true, name: 'proposalIndex' },
      { type: 'uint256', indexed: false, name: 'amount' },
    ],
  },
  {
    type: 'event',
    name: 'ProposalDelivered',
    inputs: [
      { type: 'uint256', indexed: true, name: 'engagementId' },
      { type: 'uint256', indexed: true, name: 'proposalIndex' },
      { type: 'uint64', indexed: false, name: 'deliveredAt' },
    ],
  },
  {
    type: 'event',
    name: 'ProposalReleased',
    inputs: [
      { type: 'uint256', indexed: true, name: 'engagementId' },
      { type: 'uint256', indexed: true, name: 'proposalIndex' },
    ],
  },
  {
    type: 'event',
    name: 'ProposalDisputed',
    inputs: [
      { type: 'uint256', indexed: true, name: 'engagementId' },
      { type: 'uint256', indexed: true, name: 'proposalIndex' },
      { type: 'address', indexed: false, name: 'by' },
    ],
  },
  {
    type: 'event',
    name: 'ProposalResolved',
    inputs: [
      { type: 'uint256', indexed: true, name: 'engagementId' },
      { type: 'uint256', indexed: true, name: 'proposalIndex' },
      { type: 'uint256', indexed: false, name: 'toLawyer' },
      { type: 'uint256', indexed: false, name: 'toClient' },
    ],
  },
  {
    type: 'event',
    name: 'ProposalRefunded',
    inputs: [
      { type: 'uint256', indexed: true, name: 'engagementId' },
      { type: 'uint256', indexed: true, name: 'proposalIndex' },
    ],
  },
  {
    type: 'event',
    name: 'TranscriptAnchored',
    inputs: [
      { type: 'uint256', indexed: true, name: 'engagementId' },
      { type: 'bytes32', indexed: false, name: 'root' },
      { type: 'uint64', indexed: false, name: 'atBlock' },
    ],
  },
  {
    type: 'event',
    name: 'EngagementClosed',
    inputs: [{ type: 'uint256', indexed: true, name: 'engagementId' }],
  },
] as const;
