// Auto-generated by contracts/script/Deploy.s.sol -- do not edit.
// Owner spec: 001-verified-legal-engagement.
export const ADDRESSES = {
  operator: '0x875b61258452B3E8d190CBa95D42527A8701D9b1' as const,
  schemaRegistry: '0xFB044fdB19Fef35cF3CF49F614Dfa13D9eEf41fB' as const,
  eas: '0x71C06c1D5977A63d6C3aE18051ec026e637fc4E3' as const,
  attestationManager: '0x44a2E2f8ecb681Edc90567C18c8E0a4714300E0A' as const,
  stubZKVerifier: '0x25e11414699E6447b8DBCcac48B56180B792cE33' as const,
  legalEngagementEscrow: '0xb908fD9f78f01Cd0E43fa8Ada3C1e54409C418cC' as const,
} as const;

export const SCHEMA_UIDS = {
  lawyer: '0x30001f7a30e752ef5fb0198687d7ec45f8e7718ebf18ea9c8ef62be77bb32e44' as const,
  client: '0x2fbe4ea1eba046347ddf9763cd853dbf26a72fccc6738bbce6dabe9cc0a49744' as const,
} as const;
