import { chromium } from "@playwright/test";
const SARAH = "0x2222000000000000000000000000000000000001";
const MARIA = "0x1111000000000000000000000000000000000001";
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto(`http://localhost:3000/`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/eth-landing.png", fullPage: true });
await page.goto(`http://localhost:3000/lawyers`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/eth-directory.png", fullPage: true });
await page.goto(`http://localhost:3000/dev/sign-in?wallet=${SARAH}&role=client&redirect=/client/cases`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(2000);
await page.screenshot({ path: "/tmp/eth-cases-client.png", fullPage: true });
await page.goto(`http://localhost:3000/api/auth/signout`); await page.waitForTimeout(300);
await page.goto(`http://localhost:3000/dev/sign-in?wallet=${MARIA}&role=lawyer&redirect=/lawyer/dashboard`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/eth-dashboard.png", fullPage: false });
await browser.close();
console.log("done");
