/**
 * Bar issuer signing key. Stored as a JWK at data/signing-key.jwk; generated by
 * scripts/seed.ts on first run. Constitution invariant 4 — this key is held by
 * the bar-issuer process exclusively; no other service can read it.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { type JWK, importJWK } from "jose";

const KEY_PATH = process.env.BAR_ISSUER_KEY_PATH ?? join(process.cwd(), "data/signing-key.jwk");

export function readJwk(): JWK {
  if (!existsSync(KEY_PATH)) {
    throw new Error(`bar issuer key missing at ${KEY_PATH} — run \`pnpm -F @lex-nova/bar-issuer seed\``);
  }
  return JSON.parse(readFileSync(KEY_PATH, "utf-8")) as JWK;
}

export async function readPublicJwk(): Promise<JWK> {
  const priv = readJwk();
  const { d: _, ...pub } = priv as JWK & { d?: string };
  return pub;
}

export async function loadSigningKey() {
  const jwk = readJwk();
  const alg = (jwk.alg as string) ?? "ES256";
  return { key: await importJWK(jwk, alg), kid: jwk.kid as string };
}

export function issuerBaseUrl(): string {
  const publicHostname = process.env.PUBLIC_HOSTNAME?.replace(/^https?:\/\//, "").replace(/\/$/, "");
  if (!publicHostname) {
    throw new Error("PUBLIC_HOSTNAME not set");
  }
  return `https://${publicHostname}/api/issuer/bar`;
}
