/**
 * Issuer signing keys. One per credential type — the bar-association issuer's
 * authority is distinct from the PID issuer's authority. Both keys live under
 * `data/` and are generated by `scripts/seed.ts` on first run.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { type JWK, importJWK } from "jose";

export type IssuerKind = "pid" | "bar";

function keyPath(kind: IssuerKind): string {
  if (kind === "pid") {
    return process.env.PID_ISSUER_KEY_PATH ?? join(process.cwd(), "data/pid-signing-key.jwk");
  }
  return process.env.BAR_ISSUER_KEY_PATH ?? join(process.cwd(), "data/bar-signing-key.jwk");
}

export function readJwk(kind: IssuerKind): JWK {
  const path = keyPath(kind);
  if (!existsSync(path)) {
    throw new Error(`${kind} issuer key missing at ${path} — run \`pnpm -F @lex-nova/issuer seed\``);
  }
  return JSON.parse(readFileSync(path, "utf-8")) as JWK;
}

export async function readPublicJwk(kind: IssuerKind): Promise<JWK> {
  const priv = readJwk(kind);
  const { d: _d, ...pub } = priv as JWK & { d?: string };
  return pub;
}

export async function loadSigningKey(kind: IssuerKind) {
  const jwk = readJwk(kind);
  const alg = (jwk.alg as string) ?? "ES256";
  return { key: await importJWK(jwk, alg), kid: jwk.kid as string };
}

export function issuerBaseUrl(kind: IssuerKind): string {
  const publicHostname = process.env.PUBLIC_HOSTNAME?.replace(/^https?:\/\//, "").replace(/\/$/, "");
  if (publicHostname) {
    return `https://${publicHostname}/api/issuer/${kind}`;
  }
  const port = process.env.ISSUER_PORT ?? "3001";
  return `http://localhost:${port}/api/issuer/${kind}`;
}
