// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Script, console} from "forge-std/Script.sol";
import {SchemaRegistry} from "@eas/SchemaRegistry.sol";
import {EAS} from "@eas/EAS.sol";
import {ISchemaRegistry} from "@eas/ISchemaRegistry.sol";
import {IEAS} from "@eas/IEAS.sol";

import {AttestationManager} from "../src/AttestationManager.sol";
import {StubZKConflictVerifier} from "../src/StubZKConflictVerifier.sol";
import {LegalEngagementEscrow} from "../src/LegalEngagementEscrow.sol";
import {IZKConflictVerifier} from "../src/interfaces/IZKConflictVerifier.sol";
import {IAttestationManager} from "../src/interfaces/IAttestationManager.sol";

/// @title Deploy
/// @notice Deploys the SchemaRegistry, EAS, AttestationManager,
///         StubZKConflictVerifier, and LegalEngagementEscrow contracts to the
///         active RPC. Writes a JSON-shaped TypeScript file to
///         apps/platform/lib/chain/addresses.ts so the platform binds against
///         the just-deployed addresses.
contract Deploy is Script {
    function run() external {
        uint256 operatorPk = vm.envUint("OPERATOR_PRIVATE_KEY");
        address operator = vm.addr(operatorPk);

        vm.startBroadcast(operatorPk);

        SchemaRegistry registry = new SchemaRegistry();
        EAS eas = new EAS(ISchemaRegistry(address(registry)));

        AttestationManager am = new AttestationManager(IEAS(address(eas)), ISchemaRegistry(address(registry)), operator);
        StubZKConflictVerifier verifier = new StubZKConflictVerifier();
        LegalEngagementEscrow escrow = new LegalEngagementEscrow(
            IAttestationManager(address(am)), IZKConflictVerifier(address(verifier)), operator
        );

        vm.stopBroadcast();

        bytes32 schemaLawyer = am.SCHEMA_LAWYER();
        bytes32 schemaClient = am.SCHEMA_CLIENT();

        console.log("operator:", operator);
        console.log("schemaRegistry:", address(registry));
        console.log("eas:", address(eas));
        console.log("attestationManager:", address(am));
        console.log("stubZKVerifier:", address(verifier));
        console.log("legalEngagementEscrow:", address(escrow));
        console.logBytes32(schemaLawyer);
        console.logBytes32(schemaClient);

        string memory ts = string.concat(
            "// Auto-generated by contracts/script/Deploy.s.sol -- do not edit.\n",
            "// Owner spec: 001-verified-legal-engagement.\n",
            "export const ADDRESSES = {\n",
            "  operator: '", vm.toString(operator), "' as const,\n",
            "  schemaRegistry: '", vm.toString(address(registry)), "' as const,\n",
            "  eas: '", vm.toString(address(eas)), "' as const,\n",
            "  attestationManager: '", vm.toString(address(am)), "' as const,\n",
            "  stubZKVerifier: '", vm.toString(address(verifier)), "' as const,\n",
            "  legalEngagementEscrow: '", vm.toString(address(escrow)), "' as const,\n",
            "} as const;\n",
            "\nexport const SCHEMA_UIDS = {\n",
            "  lawyer: '", vm.toString(schemaLawyer), "' as const,\n",
            "  client: '", vm.toString(schemaClient), "' as const,\n",
            "} as const;\n"
        );
        vm.writeFile("../apps/platform/lib/chain/addresses.ts", ts);
    }
}
