/**
 * Issuer signing keys. One per credential type — the bar-association issuer's
 * authority is distinct from the PID issuer's authority. Both keys live under
 * `data/` and are generated by `scripts/seed.ts` on first run.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { type JWK, importJWK } from "jose";

export type IssuerKind = "pid" | "bar";

function keyPath(kind: IssuerKind): string {
  if (kind === "pid") {
    return process.env.PID_ISSUER_KEY_PATH ?? join(process.cwd(), "data/pid-signing-key.jwk");
  }
  return process.env.BAR_ISSUER_KEY_PATH ?? join(process.cwd(), "data/bar-signing-key.jwk");
}

export function readJwk(kind: IssuerKind): JWK {
  const path = keyPath(kind);
  if (!existsSync(path)) {
    throw new Error(`${kind} issuer key missing at ${path} — run \`pnpm --filter @firmus/issuer seed\``);
  }
  return JSON.parse(readFileSync(path, "utf-8")) as JWK;
}

export async function readPublicJwk(kind: IssuerKind): Promise<JWK> {
  const priv = readJwk(kind);
  const { d: _d, ...pub } = priv as JWK & { d?: string };
  return pub;
}

export async function loadSigningKey(kind: IssuerKind) {
  const jwk = readJwk(kind);
  const alg = (jwk.alg as string) ?? "ES256";
  return { key: await importJWK(jwk, alg), kid: jwk.kid as string };
}

/**
 * External base URL the wallet uses to fetch metadata + endpoints. The /issuer
 * prefix matches the issuer app's basePath — the proxy routes /issuer/* here,
 * and the wallet's view is e.g. `https://<host>/issuer/api/issuer/pid`.
 */
export function issuerBaseUrl(kind: IssuerKind): string {
  const publicHostname = process.env.PUBLIC_HOSTNAME?.replace(/\/$/, "");
  if (publicHostname) {
    const withScheme = /^https?:\/\//.test(publicHostname) ? publicHostname : `https://${publicHostname}`;
    return `${withScheme}/issuer/api/issuer/${kind}`;
  }
  // Local-dev fallback. wwwallet can't reach localhost over HTTPS; tunnel via
  // ngrok and set PUBLIC_HOSTNAME for end-to-end tests.
  const port = process.env.PROXY_PORT ?? "3000";
  return `http://localhost:${port}/issuer/api/issuer/${kind}`;
}
